=== zyouke/zyouke/crawler/src/main/resources/crawler_css.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://103.82.53.221:9000/home/document/schema" xmlns="http://103.82.53.221:9000/home/document/schema"
	elementFormDefault="qualified">
	<xs:element name="depths">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="depth" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="depth">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="webpage" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="cssSelector" type="xs:string" use="optional" />
			<xs:attribute name="webpageParentCssSelector" type="xs:string" use="optional" />
			<xs:attribute name="lastPageCssSelector" type="xs:string" use="optional" />
			<xs:attribute name="nextPageCssSelector" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
	<xs:element name="webpage">
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="lastId" type="xs:string" use="optional"/>
			<xs:attribute name="cssSelector" type="xs:string" use="optional" />
			<xs:attribute name="index" type="xs:int" use="optional" />
			<xs:attribute name="isStorage" type="xs:boolean" use="optional" />
			<xs:attribute name="isRequest" type="xs:boolean" use="optional" />
			<xs:attribute name="orderNum" type="xs:int" use="optional" />
			<xs:attribute name="name" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zyouke/zyouke/crawler/src/test/resources/crawler_css.xml
<?xml version="1.0" encoding="UTF-8"?>
<depths xmlns="http://103.82.53.221:9000/home/document/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://103.82.53.221:9000/home/document/schema http://103.82.53.221:9000/home/document/schema/crawler_css.xsd">
	<depth webpageParentCssSelector="#cityTable tr">
		<webpage name="provinceName" index="0" cssSelector="td" />
		<webpage name="cityName" cssSelector="a" />
	</depth>
	<depth>
		<webpage cssSelector="#companylist a" />
	</depth>
	<depth nextPageCssSelector="#yw1 li.next a" lastPageCssSelector="#yw1 li.last a">
		<webpage name="companyName" cssSelector="ul.companylist li p.listleft a" />
	</depth>
	<depth>
		<webpage name="contactPerson" index="0" cssSelector="#company_info dl dd" />
		<webpage name="companyAddr" index="3" cssSelector="#company_info dl dd" />
	</depth>
</depths>

=== zyouke/zyouke/zyouke_crawler/src/test/resources/crawler_css_area.xml
<?xml version="1.0" encoding="UTF-8"?>
<depths xmlns="http://103.82.53.221:9000/home/document/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://103.82.53.221:9000/home/document/schema http://103.82.53.221:9000/home/document/schema/crawler_css.xsd">
	<depth>
		<webpage name="value" cssSelector="tr .provincetr a" />
	</depth>
	<depth webpageParentCssSelector="tr .citytr">
		<webpage name="code" index="0" cssSelector="a" />
		<webpage name="value" index="1" isRequest="false" cssSelector="a" />
	</depth>
	<depth webpageParentCssSelector="tr .countytr">
		<webpage name="code" index="0" cssSelector="a" />
		<webpage name="value" index="1" isRequest="false" cssSelector="a" />
	</depth>
	<depth webpageParentCssSelector="tr .towntr">
		<webpage name="code" index="0" cssSelector="a" />
		<webpage name="value" index="1" isRequest="false" cssSelector="a" />
	</depth>
	<depth webpageParentCssSelector="tr .villagetr">
		<webpage name="code" index="0" cssSelector="td" />
		<webpage name="value" index="2" cssSelector="td" />
	</depth>
</depths>
